import { Inter } from "next/font/google";
import Header from '@/components/Header'
import "./globals.css";
import { getSession } from '@/utils/auth'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// email:
// 'fsdfsdfsdf@asdasd123'
// id:
// 3
// userName:
// '123123'

export default async function RootLayout({ children }) {

  const userSession = await getSession();
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header user={userSession?.user} />
         {children}
      </body>
    </html>
  );
}
